### ISSUE TITLE
no signature display with fully-compliant document

### ISSUE THREAD

**Issue by ousia** [veraPDF/veraPDF-arlington-tools#2]
@veraPDF,

the [attached document a.pdf](https://github.com/user-attachments/files/15746572/a.pdf) contains a digital signature.

Checking for Arlignton and Features (with `arlington-pdf-model-checker-gui-1.27.16`), I get no deviations:

``` xml
<arlingtonReport jobEndStatus="normal" profileName="Arlington PDF 1.7 profile" statement="PDF file is compliant with Profile requirements." isCompliant="true">
        <details deviations="0"></details>
 </arlingtonReport>
```

But for some unknown reason to me, _Acrobat Reader_ is not displaying the signature pane (or any digital signature) at all with this document (both `pdfsig` and `mutool sign` detect the signature)..

I’m aware that this may be a bug in Acrobat (and this repository wouldn’t be the place to report it), but I suspect that the checker (or the Arlington model) may be missing a rule in this case.

Could you confirm that the signature not being displayed is an issue in the document viewer?

Many thanks for your help.

**Comment by bdoubrov** [comment]
Yes, Arlington model does not cover cryptographic validity of the PDF document. Please report all issues specific to the Arlington model itself at https://github.com/pdf-association/arlington-pdf-model
