### ISSUE TITLE
no warning about wrong signature

### ISSUE THREAD

**Issue by ousia** [veraPDF/veraPDF-arlington-tools#3]
@veraPDF,

the [attached uncompressed document](https://github.com/user-attachments/files/15746589/uncompressed-a.pdf) contains a signature (if relevant `/SubFilter /adbe.pkcs7.detached`).

To ensure it is broken, I uncompressed the already signed document.

I’m using `arlington-pdf-model-checker-gui-1.27.16` to check both Arlignton and Features (with all features selected).

Besides getting no deviations from Arlignton (already reported in #2), it is a bit surprising to get no mention that the signature is wrong (simple SHA256 mismatch).

Since both features (signatures and document security) have been selected, it would be important to give a warning message that the signature validity is not checked at all.

It would be great that the checker could also check the signature validity, but while this check is not being performed, it is essential to warn the user on this. 

Many thanks for your help.

**Comment by bdoubrov** [comment]
This is correct: cryptographic signature validation is outside of the scope of both veraPDF and Arlington.
