### ISSUE TITLE
Arlington questions

### ISSUE THREAD

**Issue by petervwyatt** [veraPDF/veraPDF-arlington-tools#6]
I love the fact you have resources to extend the implementation of Arlington!  Thank you!

A few questions regarding veraPDF's support for the Arlington model and PDF files:

* how do you report **Metadata** and **AF** entries that are supposedly allowed anywhere, but in reality can only be in places where indirect objects are allowed? The Arlington Model reflects ISO 32000 as it is written which means the model only explicitly includes these entries when the spec does - thus not everywhere that they're allowed. See also [PDF Errata #403](https://github.com/pdf-association/pdf-issues/issues/403) where specific invalid locations were identified - this is NOT yet encoded into the Arlington model.

* does veraPDF check object numbers against the Trailer Size entry?

* does veraPDF check or validate some of the primitive types in the Arlington model? e.g. dates are valid date strings, the correct sub-class of string (e.g. ASCII string doesn't have Unicode BOMs, etc), that `rect` arrays have 4 entries, that matrices have 6, etc.? 

* does veraPDF report against the legacy "architectural limitations"? e.g. out of range integers or reals; names > 127 bytes; strings > 64KB, etc. I know we got rid of the single vendor-specific ISO 32000-1:2008 Annex C and rewrote it to be vendor- and CPU-neutral, but many implementations still have such restrictions so having an option to report as warnings (not errors!) would be good as it is a form of incompatibility.

* how does veraPDF handle "hybrid reference" PDFs? I assume veraPDF is classed as a "PDF 1.5 processor" so it should process both the conventional cross-reference sections _and_ the cross-reference streams, but can it also "dumb down" to a pre-PDF 1.5 processor and then validate ONLY a PDF file as seen by processors that do not support PDF 1.5 (and thus only check against conventional cross reference sections)?

* can you be more precise about exactly what checks are performed for "_extends Arlington model for checking name and number tree node dictionaries (ISO 32000-2:2020, Tables 36 and 37)_"? 

* do you support or ignore `fn:Extension`?

**Comment by petervwyatt** [comment]
Where do you stand with respect to reporting "custom" but well-known structure attribute keys against the defined owners? e.g. if owner is CSS-1, CSS-2, CSS-3 then it is known what the set of custom keys might be such as `text-align`, `line-height`, etc.  Do you report or suppress? Is this configurable?

**Comment by MaximPlusov** [comment]
`can you be more precise about exactly what checks are performed for "extends Arlington model for checking name and number tree node dictionaries (ISO 32000-2:2020, Tables 36 and 37)"?`

- NameTreeNode shall not contain entries except Kids, Limits, Names.
- Entry Kids in NameTreeNode shall have type Array.
- Entry Kids in NameTreeNode is required, when fn:Not(fn:IsPresent(Names)).
- Entry Kids with type Array in NameTreeNode shall satisfy special case: fn:Not(fn:IsPresent(fn:IsPresent(Names))).
- Entry Limits in NameTreeNode shall have type Array.
- Entry Names in NameTreeNode shall have type Array.
- Entry Names in NameTreeNode is required, when fn:Not(fn:IsPresent(Kids)).
- Entry Names with type Array in NameTreeNode shall satisfy special case: fn:Not(fn:IsPresent(fn:IsPresent(Kids))).
- NameTreeNodeLimitsArray shall contain exactly 2 elements.
- Entry 0 in NameTreeNodeLimitsArray shall have type String.
- Entry 1 in NameTreeNodeLimitsArray shall have type String.
- NameTreeNodeNamesArray shall contain 2 * n elements.
- NameTreeNodeNamesArraySubArray shall contain exactly 2 elements check.
- Entry 0 in NameTreeNodeNamesArraySubArray shall have type String.
- Entry in NameTreeNodesArray shall have type Dictionary.
----------
- NumberTreeNode shall not contain entries except Kids, Limits, Nums.
- Entry Kids in NumberTreeNode shall have type Array
- Entry Kids in NumberTreeNode is required, when fn:Not(fn:IsPresent(Nums))
- Entry Kids with type Array in NumberTreeNode shall satisfy special case: fn:Not(fn:IsPresent(fn:IsPresent(Nums)))
- Entry Limits in NumberTreeNode shall have type Array
- Entry Nums in NumberTreeNode shall have type Array
- Entry Nums in NumberTreeNode is required, when fn:Not(fn:IsPresent(Kids))
- Entry Nums with type Array in NumberTreeNode shall satisfy special case: fn:Not(fn:IsPresent(fn:IsPresent(Kids))) &amp;&amp; fn:ArraySortAscending(Nums, 2)
- NumberTreeNodeLimitsArray shall contain exactly 2 elements
- Entry 0 in NumberTreeNodeLimitsArray shall have type Integer
- Entry 1 in NumberTreeNodeLimitsArray shall have type Integer
- NumberTreeNodeNumsArray shall contain 2 * n elements
- NumberTreeNodeNumsArraySubArray shall contain exactly 2 elements
- Entry 0 in NumberTreeNodeNumsArraySubArray shall have type Integer
- Entry in NumberTreeNodesArray shall have type Dictionary

**Comment by MaximPlusov** [comment]
`Where do you stand with respect to reporting "custom" but well-known structure attribute keys against the defined owners? e.g. if owner is CSS-1, CSS-2, CSS-3 then it is known what the set of custom keys might be such as text-align, line-height, etc. Do you report or suppress? Is this configurable?`
veraPDF Arlington checker report such custom keys as deviations, it is not configurable now.

**Comment by MaximPlusov** [comment]
`does veraPDF check or validate some of the primitive types in the Arlington model? e.g. dates are valid date strings, the correct sub-class of string (e.g. ASCII string doesn't have Unicode BOMs, etc), that rect arrays have 4 entries, that matrices have 6, etc.?`
yes. veraPDF Arlington checker includes all listed checks.

**Comment by MaximPlusov** [comment]
`do you support or ignore fn:Extension?`

Support of the `fn:Extension` is one of the latest feature. It is included in CLI and GUI, but not in rest yet
![image](https://github.com/veraPDF/veraPDF-arlington-tools/assets/36183885/40847424-61c1-4fe9-bba1-c5fa8fce833f)

**Comment by MaximPlusov** [comment]
`how do you report Metadata and AF entries that are supposedly allowed anywhere, but in reality can only be in places where indirect objects are allowed? The Arlington Model reflects ISO 32000 as it is written which means the model only explicitly includes these entries when the spec does - thus not everywhere that they're allowed. See also https://github.com/pdf-association/pdf-issues/issues/403 where specific invalid locations were identified - this is NOT yet encoded into the Arlington model.`
veraPDF Arlington cheker reports as error if PDF object contains Metadata/AF entries, but corresponding Arlington model object does not contain these entries.

**Comment by MaximPlusov** [comment]
`how does veraPDF handle "hybrid reference" PDFs? I assume veraPDF is classed as a "PDF 1.5 processor" so it should process both the conventional cross-reference sections and the cross-reference streams, but can it also "dumb down" to a pre-PDF 1.5 processor and then validate ONLY a PDF file as seen by processors that do not support PDF 1.5 (and thus only check against conventional cross reference sections)?`
veraPDF can’t "dumb down" to a pre-PDF 1.5 processor. veraPDF Arlington checker only reports as deviations when PDF with version < 1.5 contains ObjectStream or XRefStream.

**Comment by MaximPlusov** [comment]
The last unanswered question:
`does veraPDF check object numbers against the Trailer Size entry?`
No directly, but if veraPDF can’t find object by object number, it shows the fine log `"Trying to get object <object number> that is not present in the document"` and considers that this object is null.

**Comment by petervwyatt** [comment]
@MaximPlusov: both ISO 32000-1 and -2, Table 15, **Size** entry clearly states "_Any object in a cross-reference section whose number is greater than this value shall be ignored and defined to be missing by a PDF reader._" - could veraPDF at least warn if this situation arises (i.e. an object number greater than **Size**)? There are demonstratable differences in viewers and PDF modifiers for this situation and the spec is crystal clear on what should be happening...

**Comment by petervwyatt** [comment]
I'd also like to get some of this included in the main README of this repo. Do you want me to propose changes via a PR?

**Comment by MaximPlusov** [comment]
> I'd also like to get some of this included in the main README of this repo. Do you want me to propose changes via a PR?

Yes please.
